[package]
name = "hello_cargo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.21.0"
gilrs = "0.10.2"
env_logger = "0.10"
eframe = "0.21.3"
rdev = "0.5.2"
enigo = "0.1.2"
winapi = "0.3.9"
